#!/bin/bash
#
# Copyright (C) 2022-2024 Rafael Zalamena
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

usage() {
  cat <<EOF
Usage: $0
  [-h] [--asan] [--doc] [--fpm] [--grpc] [--help] [--jobs=NUMBER]
  [--scan-build] [--snmp] [--tsan]

Options:
  --asan: build FRR with address sanitizer.
  --tsan: build FRR with thread sanitizer.
  --doc: configure FRR to enable documentation builds (requires sphinx).
  --fpm: build FRR with forwarding plane manager.
  --grpc: enable gRPC support.
  --help or -h: this help message.
  --jobs: amount of parallel build jobs (defaults to $jobs).
  --scan-build: use clang static analyzer (compilation is way slower).
  --snmp: build FRR with SNMP support.
EOF
  exit 1
}

source_dir="/usr/src/frr"

flags=(
  --enable-multipath=64
  --prefix=/usr
  --localstatedir=/var/run/frr
  --sysconfdir=/etc/frr
  --sbindir=/usr/lib/frr
  --enable-user=frr
  --enable-group=frr
  --enable-vty-group=frrvty
  --enable-nhrpd
  --enable-sharpd
  --enable-configfile-mask=0640
  --enable-logfile-mask=0640
  --enable-dev-build
  --with-pkg-git-version
)
jobs=$(expr $(nproc))
scan_build=no

longopts='asan,doc,fpm,grpc,help,jobs:,scan-build,snmp,tsan'
shortopts='h'
options=$(getopt -u --longoptions "$longopts" "$shortopts" $*)
if [ $? -ne 0 ]; then
  usage
  exit 1
fi

set -- $options
while [ $# -ne 0 ]; do
  case "$1" in
    --asan)
      flags+=(--enable-address-sanitizer);
      shift
      ;;
    --doc)
      flags+=(--enable-doc)
      flags+=(--enable-doc-html)
      shift
      ;;
    --fpm)
      flags+=(--enable-fpm)
      shift
      ;;
    --grpc)
      flags+=(--enable-grpc)
      shift
      ;;
    --jobs)
      jobs="$2"
      shift 2
      ;;
    --scan-build)
      scan_build=yes
      shift
      ;;
    --snmp)
      flags+=(--enable-snmp=agentx)
      shift
      ;;
    --tsan)
      flags+=(--enable-thread-sanitizer);
      shift
      ;;
    -h | --help)
      usage
      shift
      ;;

    --) shift ;;
    *) echo "unhandled argument '$1'" 2>&1 ; exit 1 ;;
  esac
done

cd $source_dir

# Bootstrap the configure file
if [ ! -f configure ]; then
  echo "=> Running bootstrap ..."
  ./bootstrap.sh
fi

# Configure if not configured
if [ ! -f Makefile ]; then
  echo "=> Running configure ..."
  ../configure 'CXXFLAGS=-O0 -g -ggdb3' ${flags[@]}
fi

# Build
if [ $scan_build = 'no' ]; then
  make --jobs=$jobs >/dev/null
else
  scan-build make --jobs=$jobs >/dev/null
fi

# Install FRR binaries
make install >/dev/null

# Copy manual part
if [ ! -d /var/log/frr ]; then
  install -m 775 -o frr -g frr -d /var/log/frr
fi

if [ ! -d /etc/frr ]; then
  install -m 775 -o frr -g frrvty -d /etc/frr
  install -m 640 -o frr -g frrvty $source_dir/tools/etc/frr/vtysh.conf \
    /etc/frr/vtysh.conf
  install -m 640 -o frr -g frr $source_dir/tools/etc/frr/frr.conf \
    /etc/frr/frr.conf
  install -m 640 -o frr -g frr $source_dir/tools/etc/frr/daemons \
    /etc/frr/daemons
fi

if [ -f $source_dir/tools/frr.service ]; then
  install -m 644 $source_dir/tools/frr.service \
    /etc/systemd/system/frr.service
fi

sync

exit 0
